{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" (include "outline.fullname" .)) }}
{{- $hasUserSecrets := or (and .Values.outline.oidc.clientId .Values.outline.oidc.clientSecret) (and .Values.outline.smtp.enabled .Values.outline.smtp.password) }}
{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-secret
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ (.Values.outline.secretKey | default (randAlphaNum 32 | sha256sum)) | b64enc | quote }}
  UTILS_SECRET: {{ (.Values.outline.utilsSecret | default (randAlphaNum 32)) | b64enc | quote }}
{{- end }}
{{- if $hasUserSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-user-secret
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.outline.oidc.clientId .Values.outline.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.outline.oidc.clientSecret | quote }}
  {{- end }}
  {{- if and .Values.outline.smtp.enabled .Values.outline.smtp.password }}
  SMTP_PASSWORD: {{ .Values.outline.smtp.password | quote }}
  {{- end }}
{{- end }}
